/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CommuneAPIConsumer } from "./CommuneAPIConsumer";
export * as factories from "./factories";
export { CommuneAPIConsumer__factory } from "./factories/CommuneAPIConsumer__factory";
