/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CommuneAPIConsumerInterface extends Interface {
  functions: {
    "data()": FunctionFragment;
    "fulfill(bytes32,uint256)": FunctionFragment;
    "isOwner()": FunctionFragment;
    "owner()": FunctionFragment;
    "requestData(string,string,int256)": FunctionFragment;
    "stringToBytes32(string)": FunctionFragment;
    "text()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdrawLink()": FunctionFragment;
  };
  getFunction(
    nameOrSignature:
      | "data"
      | "fulfill"
      | "isOwner"
      | "owner"
      | "requestData"
      | "stringToBytes32"
      | "transferOwnership"
      | "withdrawLink"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChainlinkCancelled"
      | "ChainlinkFulfilled"
      | "ChainlinkRequested"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "data", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fulfill",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestData",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stringToBytes32",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawLink",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "data", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fulfill", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stringToBytes32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawLink",
    data: BytesLike
  ): Result;
}

export namespace ChainlinkCancelledEvent {
  export type InputTuple = [id: BytesLike];
  export type OutputTuple = [id: string];
  export interface OutputObject {
    id: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainlinkFulfilledEvent {
  export type InputTuple = [id: BytesLike];
  export type OutputTuple = [id: string];
  export interface OutputObject {
    id: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainlinkRequestedEvent {
  export type InputTuple = [id: BytesLike];
  export type OutputTuple = [id: string];
  export interface OutputObject {
    id: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CommuneAPIConsumer extends BaseContract {
  connect(runner?: ContractRunner | null): CommuneAPIConsumer;
  waitForDeployment(): Promise<this>;

  interface: CommuneAPIConsumerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  data: TypedContractMethod<[], [bigint], "view">;

  fulfill: TypedContractMethod<
    [_requestId: BytesLike, _data: BigNumberish],
    [void],
    "nonpayable"
  >;

  isOwner: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  requestData: TypedContractMethod<
    [url: string, path: string, timesAmount: BigNumberish],
    [string],
    "nonpayable"
  >;

  stringToBytes32: TypedContractMethod<[src: string], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawLink: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "data"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fulfill"
  ): TypedContractMethod<
    [_requestId: BytesLike, _data: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isOwner"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestData"
  ): TypedContractMethod<
    [url: string, path: string, timesAmount: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stringToBytes32"
  ): TypedContractMethod<[src: string], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawLink"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ChainlinkCancelled"
  ): TypedContractEvent<
    ChainlinkCancelledEvent.InputTuple,
    ChainlinkCancelledEvent.OutputTuple,
    ChainlinkCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ChainlinkFulfilled"
  ): TypedContractEvent<
    ChainlinkFulfilledEvent.InputTuple,
    ChainlinkFulfilledEvent.OutputTuple,
    ChainlinkFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "ChainlinkRequested"
  ): TypedContractEvent<
    ChainlinkRequestedEvent.InputTuple,
    ChainlinkRequestedEvent.OutputTuple,
    ChainlinkRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ChainlinkCancelled(bytes32)": TypedContractEvent<
      ChainlinkCancelledEvent.InputTuple,
      ChainlinkCancelledEvent.OutputTuple,
      ChainlinkCancelledEvent.OutputObject
    >;
    ChainlinkCancelled: TypedContractEvent<
      ChainlinkCancelledEvent.InputTuple,
      ChainlinkCancelledEvent.OutputTuple,
      ChainlinkCancelledEvent.OutputObject
    >;

    "ChainlinkFulfilled(bytes32)": TypedContractEvent<
      ChainlinkFulfilledEvent.InputTuple,
      ChainlinkFulfilledEvent.OutputTuple,
      ChainlinkFulfilledEvent.OutputObject
    >;
    ChainlinkFulfilled: TypedContractEvent<
      ChainlinkFulfilledEvent.InputTuple,
      ChainlinkFulfilledEvent.OutputTuple,
      ChainlinkFulfilledEvent.OutputObject
    >;

    "ChainlinkRequested(bytes32)": TypedContractEvent<
      ChainlinkRequestedEvent.InputTuple,
      ChainlinkRequestedEvent.OutputTuple,
      ChainlinkRequestedEvent.OutputObject
    >;
    ChainlinkRequested: TypedContractEvent<
      ChainlinkRequestedEvent.InputTuple,
      ChainlinkRequestedEvent.OutputTuple,
      ChainlinkRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
